### ISSUE TITLE
ToggleBaseMenuProps - interface has been removed

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/pf-codemods#165] opened 2022-12-08 13:51 UTC
Follow up to breaking change PR https://github.com/patternfly/patternfly-react/pull/8235

Any consumer importing ToggleBaseMenuProps should be warned that it no longer exists. Or possibly the code mod can remove the import statement and any reference to the interface? @jenny-s51 is there anything else that should be considered?

_Required actions:_
1. Build codemod
2. Build test
3. Update readme with description & example

**Comment by jenny-s51** [comment] 2022-12-21 16:33
@nicolethoen I think we can warn the consumer that the interface has been removed, and maybe provide a template for replacing it with `menuAppendTo` from a specific component [similar to how Keycloak did this](https://github.com/keycloak/keycloak-ui/pull/2613/files#diff-fa490fae1daac3c2b0fd391ed480010caf7a27b915ceee5b3f031fa7eaa3be5aL26)/! Also this seems to be a duplicate of #143 which was opened first - closing as a duplicate if that's okay.

**Comment by jenny-s51** [comment] 2022-12-21 16:34
Also this seems to be a duplicate of #143 which was opened first - closing as a duplicate if that's okay.

**Closed** 2022-12-21 16:34 UTC
